[package]
name = "v9r-orchestrator"
version.workspace = true
edition.workspace = true

[dependencies]
v9r-core = { workspace = true }
v9r-vfs = { workspace = true }
v9r-cap = { workspace = true }
v9r-runtime = { workspace = true }
tokio = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
toml = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
